[package]
name = "skip_lists_sorted"
version = "0.1.0"
authors = ["Marty Stumpf <thealmartyblog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.4.0"